server:
  port: 8091

#选择指定的配置文件{druid}
spring:
  thymeleaf:
    cache: false
    prefix: classspath:/templates/
    suffix: .html

#spring.thymeleaf.cache=false
#spring.thymeleaf.prefix=classpath:/templates/
#spring.thymeleaf.suffix=.html
#spring.thymeleaf.encoding=UTF-8
#spring.thymeleaf.content-type=text/html
#spring.thymeleaf.mode=HTML5
